services:
  mongo_abook:
    image: mongo:8.0.17
    container_name: mongo_abook
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nikelroot
      - MONGO_INITDB_ROOT_PASSWORD=48151623MongoDB42
      - NODE_ENV=production
      - TZ=Asia/Yekaterinburg
    command: [
        'mongod',
        '--bind_ip_all',
        '--wiredTigerCacheSizeGB=3', # ~25–35% от лимита памяти
        '--setParameter=ttlMonitorSleepSecs=60' # реже будить TTL-монитор (опционально)
      ]
    volumes:
      - ./a_db7:/data/db
    #      - /etc/localtime:/etc/localtime:ro
    #      - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      abook:
      main:
        ipv4_address: 192.168.28.11
        mac_address: 3e:2f:83:b2:5b:ef
    mem_limit: 1g # лимит памяти контейнера
    memswap_limit: 1g # запретить уходить в своп
    ulimits:
      nofile:
        soft: 64000
        hard: 64000

networks:
  main:
    external: true
  abook:
    external: true
